#!/bin/sh

hostname=mini2440
eth0.serverip=192.168.1.205
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=empty

# or set your networking parameters here
eth0.ipaddr=192.168.1.121
eth0.netmask=255.255.255.0
eth0.gateway=192.168.1.1
eth0.serverip=192.168.1.205

# can be either 'nfs', 'tftp' or 'nand'
kernel_loc=nand
# can be either 'net', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-${hostname}.${rootfs_type}

kernelimage=zImage-${hostname}
#kernelimage=uImage-$hostname
#kernelimage=Image-$hostname
#kernelimage=Image-$hostname.lzo

if [ -n $user ]; then
	kernelimage="${user}"-"${kernelimage}"
	nfsroot="${eth0.serverip}:/home/${user}/nfsroot/${hostname}"
	rootfsimage="${user}"-"${rootfsimage}"
else
	nfsroot="${eth0.serverip}:/tftproot/mini2440/rootfs"
fi

autoboot_timeout=1

#
# "mini2440" kernel parameter
# 0 .. 9 = screen type
# b = backlight enabled
# t = touch enabled
# c = camera enabled
# Note: can be "minit2440= " if nothing of these components are connected
#
bootargs="console=ttySAC0,115200 mini2440=0tbc"

# TODO NOR support

nand_device="nand"
nand_parts="256k(barebox),128k(bareboxenv),5120k(kernel),-(root)"
rootfs_mtdblock_nand=3
